### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by bambokianr** [bambokianr/finance-manager-front#5]
- [x] Tela de cadastro
- [x] Tela de login
- [x] Autenticação do usuário - hook
- [x] Autenticação do usuário - integração back-end

----- Dashboard -----
- [x] Criar um componente específico para `select`
- [x] Criação de uma nova despesa: filtro, valor, descrição, checkbox se já foi paga ou não (se não foi paga, checkbox de criar lembrete)
- [x] Integração com o google calendar
- [x] Adicionar gráfico - uso da lib `recharts`
- [x] Modal de listagem de todos os gastos de um usuário - editar e excluir dados existentes
- [x] Tornar o dashboard minimamente responsivo
- [x] Fechar modal assim que despesas são criadas ou editadas/salvas
- [x] Tag obrigatória - enviar um evento p/ componente Select => tratar se o valor da ref é 'all' - aplicar o erro
- [x] Adicionar tag no yup - select
- [x] Options - chart select (texto não aparece)
- [x] Logo?
- [x] Limpar código

----- Integração -----
- [x] `POST /user`
- [x] `POST /user/login`
- [x] `POST /tag`
- [x] `POST /expense`
- [x] `DELETE /expense`
- [x] `PUT /expense`
- [x] `GET /expenses`
- [x] `GET /tags`
- [x] `GET /expensesToChart`
